# Generated by Django 4.2 on 2025-03-09 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                ("conteudo", models.TextField(verbose_name="Conteúdo")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("PES", "Pessoal"),
                            ("COR", "Corporativo"),
                            ("EST", "Estudantil"),
                            ("OUT", "Outros"),
                        ],
                        default="PES",
                        max_length=3,
                        verbose_name="Categoria",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
